apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: pvr
build:
  artifacts:
    - image: pvr-php
      context: .
      docker:
        target: frankenphp_prod

deploy:
  helm:
    releases:
    - name: pvr
      chartPath: helm/pvr
      namespace: default
      setValueTemplates:
        php.image.repository: "{{.IMAGE_REPO_pvr_php}}"
        php.image.tag: "{{.IMAGE_TAG_pvr_php}}@{{.IMAGE_DIGEST_pvr_php}}"
      valuesFiles:
        - skaffold-values.yaml
